Super/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import HomeView
from order.views import OrderView

#from product.views import Home

urlpatterns = [
    url(r'^$',HomeView.as_view(template_name='index.html'),name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^product/', include("product.urls")),
    url(r"^account/", include("account.urls")),
    url(r"^cart/", include("cart.urls")),
    url(r'^checkout/',OrderView.as_view(),name='checkout'),
    

    url(r'^something/paypal/', include('paypal.standard.ipn.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import include,url,patterns
from .views import CartView,ajaxCartForm
urlpatterns = patterns(
	"",
	url(r'^$', CartView.as_view(),name="cart"),
	url(r'^ajax/cart/$', ajaxCartForm),
)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product 
from account.models import Account


# Create your models here.
class Cart(models.Model):
	user = models.ForeignKey(User)
	product = models.ForeignKey(Product)
	quantity = models.IntegerField(default=1)
	created_on = models.DateTimeField(auto_now_add = True)
	modified_on = models.DateTimeField(auto_now_add = True)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
#from autoslug import AutoSlugField
# Create your models here.



DISTRICT_CHOICE = [
    ('KTM','Kathmandu'),
    ('LIT','Lalitpur'),
    ('BKT','Bhaktapur')
    ]


class Location(models.Model):
    district = models.CharField(choices=DISTRICT_CHOICE, max_length=10)
    village = models.CharField(max_length=100)
    ward_no = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return "%s %s %s" %(self.district, self.village, self.ward_no)


class Category(MPTTModel):
    name=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    class MPTTMeta:
            order_insertion_by = ['name']

    def __str__(self):
            return self.name


##class Category(models.Model):
##    name = models.CharField(max_length=200)
##    slug = models.SlugField(unique=True)
##    parent = models.ForeignKey('self', blank=True, null=True)
##
##    def __str__(self):
##        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=11)
    qty = models.IntegerField()
    location = models.ForeignKey(Location)
    manufacturer = models.ForeignKey(User)
    category = TreeForeignKey('Category', null=True, blank=True, db_index=True)
##    category = models.ForeignKey(Category)
##    photo = models.ImageField(upload_to='Product_images',blank = True, null = True)
    def get_manufacture_email(self):
        return self.manufacturer.email
    get_manufacture_email.short_description = 'Email'


    def __str__(self):
        return self.name

    def get_avg_rating(self):
        from comments.models import Comments
        avg =Comments.average_rating(self)
        return avg    

class ProductImage(models.Model):
    photo = models.ImageField(upload_to='Product_images',blank = True, null = True)
    obj = models.ForeignKey(Product)

cart/views.py
from django.shortcuts import render


# Create your views here.
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Sum,Avg

import json
from product.models import Product
from .models import Cart

class CartView(ListView):
    template_name = 'cart/cart.html'
    
    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user)
    
    
    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        cart = Cart.objects.filter(user=self.request.user)
      
        sub_total = 0
        for c in cart:
            sub_total += c.product.price * c.quantity
        context['sub_total'] = sub_total
        return context


@csrf_exempt
def ajaxCartForm(request):
    if(request.method == 'POST'):
       
        cart, isCreated = Cart.objects.get_or_create(user = request.user, product_id = request.POST['product_id'])
    
        if isCreated:
            cart.quantity = request.POST['quantity']
        else:
            cart.quantity = cart.quantity + int(request.POST['quantity'])

        cart.save()



        response_data = {}
        data = {
                'cart':cart.id
                }
        response_data['result'] = 'Sucess'
        response_data['data'] = data

        return HttpResponse(json.dumps(response_data), content_type='application/json')

templates/cart/cart.html
{% extends 'base.html' %}
{% load staticfiles product_category %}

{% block content %}
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description">Name</td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<tr>
						{% for cart in cart_list%}

							<td class="cart_product">
								<a href=""><img src="/media/{{cart.product.productimage_set.all.0.photo }}"alt="" height="20" width="20"></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{ cart.product.name }}</a></h4>
								<p>Web ID: {{ cart.product.id }}</p>
							</td>
							<td class="cart_price">
								<p>{{cart.product.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="{{ cart.quantity }}" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">{{cart.product.price|mul:cart.quantity}}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>

						{% endfor %}


						<td colspan="4">&nbsp;</td>
							<td colspan="2">
								<table class="table table-condensed total-result">
									<tr>
										<td>Cart Sub Total</td>
										<td id="sub_total">${{ sub_total }}</td>
									</tr>
									<tr>
										<td>Exo Tax</td>
										<td>$0</td>
									</tr>
									<tr class="shipping-cost">
										<td>Shipping Cost</td>
										<td>Free</td>										
									</tr>
									<tr>
										<td>Total</td>
										<td><span id="total_amount">$0</span></td>
									</tr>
								</table>
							</td>
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<!--<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<input type="checkbox">
								<label>Use Coupon Code</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Use Gift Voucher</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Estimate Shipping & Taxes</label>
							</li>
						</ul>
						<ul class="user_info">
							<li class="single_field">
								<label>Country:</label>
								<select>
									<option>United States</option>
									<option>Bangladesh</option>
									<option>UK</option>
									<option>India</option>
									<option>Pakistan</option>
									<option>Ucrane</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
								
							</li>
							<li class="single_field">
								<label>Region / State:</label>
								<select>
									<option>Select</option>
									<option>Dhaka</option>
									<option>London</option>
									<option>Dillih</option>
									<option>Lahore</option>
									<option>Alaska</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
							
							</li>
							<li class="single_field zip-field">
								<label>Zip Code:</label>
								<input type="text">
							</li>
						</ul>
						<a class="btn btn-default update" href="">Get Quotes</a>
						<a class="btn btn-default check_out" href="">Continue</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li>Cart Sub Total <span>$59</span></li>
							<li>Eco Tax <span>$2</span></li>
							<li>Shipping Cost <span>Free</span></li>
							<li>Total <span>$61</span></li>
						</ul>
							<a class="btn btn-default update" href="">Update</a>
							<a class="btn btn-default check_out" href="">Check Out</a>
					</div>
				</div>
			</div>
		</div>
	</section>--><!--/#do_action-->
{% endblock %}
{% block left_sidebar %}
{% endblock %}

	
	