Super/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import HomeView
from order.views import OrderView

#from product.views import Home

urlpatterns = [
    url(r'^$',HomeView.as_view(template_name='index.html'),name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^product/', include("product.urls")),
    url(r"^account/", include("account.urls")),
    url(r"^cart/", include("cart.urls")),
    url(r'^checkout/',OrderView.as_view(),name='checkout'),
    

    url(r'^something/paypal/', include('paypal.standard.ipn.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import include,url,patterns
from .views import CartView,ajaxCartForm
urlpatterns = patterns(
	"",
	url(r'^$', CartView.as_view(),name="cart"),
	url(r'^ajax/cart/$', ajaxCartForm),
)

product/urls.py
from django.conf.urls import include,url,patterns
from .views import ProductListView,ProductDetailView, ajaxCommentForm


urlpatterns = patterns(
    "",
    url(r'^$', ProductListView.as_view(),name='productlist'),
    url(r'^(?P<pk>\d+)/$',ProductDetailView.as_view(),name='productdetail'),
    url(r'^(?P<slug>[-\w]+)/$',ProductDetailView.as_view(),name='productdetail'),

    url(r'^ajax/comment/$', ajaxCommentForm )
)

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from account.models import Account
from product.models import Product
from django.db.models import Sum,Avg
# Create your models here.


RATING_CHOICES = [
    (0,0),
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
]


class Comments(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    created_on = models.DateTimeField(auto_now_add = True)
    modified_on = models.DateTimeField(auto_now_add = True)
    comments = models.TextField(max_length = 500, null = True, blank = True)
    rating = models.IntegerField(choices = RATING_CHOICES, default = 0)



    @staticmethod
    def average_rating(self):
        all_comments=Comments.objects.filter(rating__gt=0)
      #  total_rating=all_comments.annonate(total=Sum('rating'))
        avg_rating=all_comments.aggregate(Avg('rating'))
        return avg_rating['rating__avg']

product/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
#from autoslug import AutoSlugField
# Create your models here.



DISTRICT_CHOICE = [
    ('KTM','Kathmandu'),
    ('LIT','Lalitpur'),
    ('BKT','Bhaktapur')
    ]


class Location(models.Model):
    district = models.CharField(choices=DISTRICT_CHOICE, max_length=10)
    village = models.CharField(max_length=100)
    ward_no = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return "%s %s %s" %(self.district, self.village, self.ward_no)


class Category(MPTTModel):
    name=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    class MPTTMeta:
            order_insertion_by = ['name']

    def __str__(self):
            return self.name


##class Category(models.Model):
##    name = models.CharField(max_length=200)
##    slug = models.SlugField(unique=True)
##    parent = models.ForeignKey('self', blank=True, null=True)
##
##    def __str__(self):
##        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=11)
    qty = models.IntegerField()
    location = models.ForeignKey(Location)
    manufacturer = models.ForeignKey(User)
    category = TreeForeignKey('Category', null=True, blank=True, db_index=True)
##    category = models.ForeignKey(Category)
##    photo = models.ImageField(upload_to='Product_images',blank = True, null = True)
    def get_manufacture_email(self):
        return self.manufacturer.email
    get_manufacture_email.short_description = 'Email'


    def __str__(self):
        return self.name

    def get_avg_rating(self):
        from comments.models import Comments
        avg =Comments.average_rating(self)
        return avg    

class ProductImage(models.Model):
    photo = models.ImageField(upload_to='Product_images',blank = True, null = True)
    obj = models.ForeignKey(Product)

product/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Product, Category
from comments.models import Comments
# Create your views here.

class ProductListView(ListView):
    model = Product
    template_name = 'product/product_list.html'
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
    ##        context['category_list'] = Category.objects.filter(parent__isnull=True)
        return context

class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
##        context['category_list'] = Category.objects.filter(parent__isnull=True)
        return context

from django.views.decorators.csrf import csrf_exempt
import json

from django.http import HttpResponse

@csrf_exempt
def ajaxCommentForm(request):

    if request.method == "POST":
        comment = Comments( user= request.user,
            product_id= request.POST['product_id'],
            comments=request.POST['comment'],
            rating= request.POST['rating']
        )
        comment.save()
        print comment
        response_data = {}
        time = comment.created_on.strftime(' %H:%M %p')
        date = comment.created_on.strftime('%Y-%b-%d')
        response_data = {"user_name": comment.user.username, 'comment_text': comment.comments, 'rating': comment.rating, 'comment_id': comment.id, 'time': time, 'date':date}

        return HttpResponse(json.dumps(response_data), content_type="application/json")

templates/product/http404.html
<p>Details are here</p>

templates/product/product_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load product_category %}

{% block content %}
<div class="col-sm-9 padding-right">

					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
						
							<div class="view-product">
								<img src="/media/{{object.productimage_set.all.0.photo }}" alt="" />
								
							</div>
							<div id="similar-product" class="carousel slide" data-ride="carousel">
								
								  <!-- Wrapper for slides -->
								    <div class="carousel-inner">
									{% for photo in object.productimage_set.all %}
										<div class="item {% if forloop.first %} active {% endif %}">
										  <a href=""><img src="{{ photo.photo.url }}" alt="" </a>
										 
										</div>
									{% endfor %}
										
										
									</div>

								  <!-- Controls -->
								  <a class="left item-control" href="#similar-product" data-slide="prev">
									<i class="fa fa-angle-left"></i>
								  </a>
								  <a class="right item-control" href="#similar-product" data-slide="next">
									<i class="fa fa-angle-right"></i>
								  </a>
							</div>

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="{% static 'images/product-details/new.jpg'%}" class="newarrival" alt="" />
								<h2>{{object.name}}</h2>
								<p>Product ID: {{object.id}}</p>
								<!-- <img src="{% static 'images/product-details/rating.png'%}" alt="" /> -->
								<span>
									<span>RS: {{object.price}}/-</span>
									<br>
									<label>Quantity:</label>
									<input type="text" id="quantity"  type="number" name="quantity" value="1" autocomplete="off" size="2" {%if object.qty == 0 %}disabled="disabled"{% endif %}/>
									<button type="button" id="add_to_cart"class="btn btn-default cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span>
								<p><b>Rating:</b> {{object.get_avg_rating|floatformat:"-3" }}</p>
									
								<p><b>Availability:</b>{%if object.qty == 0 %}Out of Stock{% else %} In Stock {% endif %}</p>
								<p><b>Condition:</b> New</p>
								<p><b>Brand:</b> E-SHOPPER</p>
								<a href=""><img src="{% static 'images/product-details/share.png'%}" class="share img-responsive"  alt="" /></a>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->
					



					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								<li class="active"><a href="#details" data-toggle="tab">Description</a></li>
								<li><a href="#reviews" data-toggle="tab">Reviews (<p id="objectnumber">{{object.comments_set.all.count}}<p>)</a></li>
							</ul>
						</div>
						<div class="tab-content">
									<div class="tab-pane fade in active" id="details" >
							{{object.description}}
						</div>
				
							<div class="tab-pane fade" id="reviews" >
								<div class="col-sm-12">
									
									
								</div>
								
								<div class="col-sm-12">
									<div id="comment_list">
										{% for comment in object.comments_set.all %}
										<ul>
											<li><a href=""><i class="fa fa-user"></i>{{ comment.user.username }}</a></li>
											<li><a href=""><i class="fa fa-clock-o"></i>{{ comment.created_on|date:"h:i A" }}</a></li>
											<li><a href=""><i class="fa fa-calendar-o"></i>{{ comment.created_on|date:"d M Y" }} </a></li>
										</ul>
										<p>{{ comment.comments }}</p>
										{% endfor %}
									</div>
									
									<p><b>Write Your Review</b></p>
									{% if request.user.is_authenticated %}
									<form action="#">
										<textarea name="comment" id="comment_text"></textarea>
										<b>Rating: </b> <input type="number" value="0" id="rating" min=0 max="5"/>
										<button type="button" class="btn btn-default pull-right comment_form_submit">
											Submit
										</button>
									</form>
									{% else %}
									<button type="button" class="btn btn-default pull-right"><a href="{% url 'account_login' %} ">signin to review</a></button>
									{% endif %}
								</div>
							</div>
							
						</div>
					</div><!--/category-tab-->
					
					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>
						
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
									
								</div>
								
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
						</div>
					</div><!--/recommended_items-->
					
				</div>
{% endblock %}	

{% block left_sidebar %}

{% show_category category_list %}

{% endblock %}		


{% block javascript %}
	<script>
		$.fn.appendComment= function (obj){
			var comment = '<ul>\
										<li><a href=""><i class="fa fa-user"></i>'+obj.user_name+'</a></li>\
										<li><a href=""><i class="fa fa-clock-o"></i>'+ obj.time +'</a></li>\
										<li><a href=""><i class="fa fa-calendar-o"></i>'+ obj.date +' </a></li>\
									</ul>\
									<p>'+obj.comment_text+'</p>';
			
			$(this).append(comment);
			$('#objectnumber').innerHTML = "12345678";
			
			
		}
	
		
		$(".comment_form_submit").click(function(){
			var comment_text = $("#comment_text").val().trim();
			var rating = $("#rating").val();
			if (comment_text == '') return false;
			
			var data = {"comment":comment_text, 'product_id':{{ object.id}}, "rating":rating }	
			$.ajax({
			  type: "POST",
			  url: '/product/ajax/comment/',
			  data: data,
			  success: successFun
			});
			
			function successFun(data){
				console.log(data);
				$("#comment_list").appendComment(data);
				$("#comment_text").val("");
				$("#rating").val('0');
			}
			
		})
	$("#add_to_cart").click(function(){
		var quantity = $("#quantity").val().trim();
			
			if (quantity == '') return false;
			
			var data = {"quantity":quantity, 'product_id':{{ object.id }} }	
			$.ajax({
			  type: "POST",
			  url: '/cart/ajax/cart/',
			  data: data,
			  success: successFun
			});
			
			function successFun(data){
				alert(data.result);
				
			}
			
		})
	</script>


{% endblock %}

templates/product/product_list.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load product_category %}
{% block content %}
<div class="col-sm-9padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						<div class="row">
						{% for product in product_list %}
						
							<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
									<a href="{{product.slug}}"><img src="/media/{{ product.productimage_set.all.0.photo }}"alt="" ></a>
										<!--<img src="/media/{{product.photo}}" alt="" />-->
										<h2>Rs. {{product.price}}</h2>
										<a href="{{product.slug}}"><p>{{product.name}}</p></a>
										<a href="{{product.slug}}" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
									</div>
								
									
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						
						</div>
						
						{% endfor %}
						</div>
						<div class="row text-center">
						<ul class="pagination ">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
						</div>
					</div><!--features_items-->
				</div>
			
{% endblock %}

{% block left_sidebar %}

{% show_category category_list %}

{% endblock %}	